package com.stencil.markups.Models;

import lombok.Data;
import lombok.Getter;
import lombok.Setter;

import javax.persistence.*;
import java.util.ArrayList;
import java.util.List;


@Entity
public @Data class House {
    //TODO: for all models, change primary key to an autogenerated id, and also choose type of generation after research
    @Id
    @Column(name = "house_index")
    private int house;

    @Column(name = "house_name")
    private String name;

    @OneToMany(mappedBy = "house")
    private List<Room> rooms = new ArrayList<>();

    @ManyToOne
    @JoinColumn(name = "users")
    private User user;

    public void addRoom(Room room){
        rooms.add(room);
    }

    public House(){}

    public House(String name) {
        this.name = name;
    }
}
